# Generated by Django 4.2.13 on 2024-08-08 12:47

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, default=''),
        ),
    ]
