# Generated by Django 4.2.13 on 2024-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_remove_profile_posts_alter_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
