# Generated by Django 4.2.13 on 2024-07-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_alter_profile_bio_alter_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_on']},
        ),
    ]
