# Generated by Django 4.2.13 on 2024-07-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0006_alter_profile_options_alter_profile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
