# Generated by Django 4.2.13 on 2024-07-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0008_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
