# Generated by Django 4.2.13 on 2024-07-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_rename_profile_pic_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_on']},
        ),
    ]
