# Generated by Django 4.2.13 on 2024-08-06 19:55

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0010_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
