# Generated by Django 4.2.13 on 2024-08-07 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('region', models.CharField(blank=True, choices=[('AF', 'Africa'), ('ASIA', 'Asia'), ('AUS', 'Australasia'), ('EU', 'Europe / UK'), ('MENA', 'Middle East'), ('SA', 'South / Central America'), ('US', 'USA / Canada')], default='', max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='0', max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
