# Generated by Django 4.2.13 on 2024-07-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_status_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('AF', 'Africa'), ('AUS', 'Australasia'), ('EU', 'Europe / UK'), ('MENA', 'Middle East'), ('SA', 'South /Central America'), ('US', 'USA / Canada')], null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
