# Generated by Django 4.2.13 on 2024-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_region_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('AF', 'Africa'), ('ASIA', 'Asia'), ('AUS', 'Australasia'), ('EU', 'Europe / UK'), ('MENA', 'Middle East'), ('SA', 'South /Central America'), ('US', 'USA / Canada')], null=True),
        ),
    ]
