# Generated by Django 4.2.13 on 2024-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_country_alter_post_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(blank=True, choices=[('AF', 'Africa'), ('ASIA', 'Asia'), ('AUS', 'Australasia'), ('EU', 'Europe / UK'), ('MENA', 'Middle East'), ('SA', 'South / Central America'), ('US', 'USA / Canada')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
