# Generated by Django 4.2.13 on 2024-08-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_page', '0010_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_name', to='profile_page.profile')),
                ('profile_pic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_pic', to='profile_page.profile')),
            ],
        ),
    ]
