# Generated by Django 4.2.13 on 2024-08-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='title', max_length=250),
            preserve_default=False,
        ),
    ]
