# Generated by Django 4.2.13 on 2024-08-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0010_alter_profile_options'),
        ('about', '0002_remove_about_name_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='profile_page.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
    ]
