# Generated by Django 4.2.13 on 2024-08-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_alter_about_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_pic',
        ),
    ]
