# Generated by Django 4.2.13 on 2024-08-06 14:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_about_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
